export {default as Home} from "./Home"
export {default as User} from "./User"
export {default as Profile} from "./profile"
export {default as Login} from "./Login"
export {default as SignUp} from "./Signup"